version: "3.8"
services:
  api-ml:
    container_name: api-ml
    network_mode: bridge
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    ports:
      - 8009:8000
      - 8888:8888