# Generated by Django 4.2.5 on 2023-09-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExternalInfraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("level", models.CharField(max_length=100)),
                ("fine", models.FloatField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
