# Generated by Django 4.2.3 on 2023-08-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensePlates', '0002_rename_hasinfraction_licenseplate_hasinfractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseplate',
            name='imageData',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
