# Generated by Django 4.2.5 on 2023-09-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("licensePlates", "0004_testimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenseplate",
            name="imageData",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
