# Generated by Django 4.2.3 on 2023-08-23 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licensePlates', '0002_rename_hasinfraction_licenseplate_hasinfractions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('fine', models.FloatField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('licensePlate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licensePlates.licenseplate')),
            ],
        ),
    ]
